### ISSUE TITLE
Include CONTRIBUTING file and CODE_OF_CONDUCT file

### ISSUE THREAD

**Issue by gpatchikoru** [SpreadSheets600/Budget-Tracker#1]
I would like to update your repository with CONTRIBUTING file and CODE_OF_CONDUCT files so that everyone can get clear idea on creating forks and contributing effortless.

Can you please assign this task to me?

**Comment by SpreadSheets600** [comment]
@gpatchikoru Sure :)
Make sure to star the repo !

**Comment by gpatchikoru** [comment]
okay thank you

**Comment by gpatchikoru** [comment]
updated the CONTRIBUTING file and CODE_OF_CONDUCT. please check the PR let me know if any changes required.
