### ISSUE TITLE
[FEATURE] - Fixed Visualization Tab Ensured that charts (bar, line, pie) displaying properly without overlapping or layout issues.

### ISSUE THREAD

**Issue by yazdanhaider** [SpreadSheets600/Budget-Tracker#12]
### Feature Summary

 Fixed Visualization Tab Ensured that charts (bar, line, pie)

### Additional Context

# [FEATURE] - Fixed Visualization Tab

## Description
Ensured that charts (bar, line, pie) display properly without overlapping or layout issues.

## Changes Made
- Fixed rendering issues for bar, line, and pie charts.
- Improved layout adjustments to prevent overlapping.

## Testing
- Verified that all chart types (bar, line, pie) render correctly in different screen resolutions.
- Confirmed no layout issues or visual overlap across multiple scenarios.

## Screenshots
<img width="1433" alt="Screenshot 2024-10-13 at 4 35 19 AM" src="https://github.com/user-attachments/assets/bb7645cb-7ebd-4ac9-b8df-82d8eb824a26">
<img width="1433" alt="Screenshot 2024-10-13 at 4 37 39 AM" src="https://github.com/user-attachments/assets/d53a9d63-94e6-488d-b6a1-c5a1d5ec9878">
<img width="1433" alt="Screenshot 2024-10-13 at 4 37 49 AM" src="https://github.com/user-attachments/assets/56434a07-c17e-47c0-bb2e-353a7c678501">

**Comment by SpreadSheets600** [comment]
@yazdanhaider thank you for such amazing work, please open up a pull request 😊
