### ISSUE TITLE
[FEATURE] - Export Data Allowing users to export their data (income, expenses, goals) to CSV format for easier analysis.

### ISSUE THREAD

**Issue by yazdanhaider** [SpreadSheets600/Budget-Tracker#13]
### Feature Summary

Export Data Allowing users to export their data

### Additional Context

# [FEATURE] - Export Data

## Description
Allowing users to export their data (income, expenses, goals) to CSV format for easier analysis.

## Changes Made
- Added functionality to export income, expenses, and goals data as a CSV file.
- Ensured the CSV format is compatible with common spreadsheet applications (e.g., Excel, Google Sheets).

## Testing
- Verified that the exported CSV file contains accurate and complete data.
- Tested CSV file compatibility with different spreadsheet applications.
- Confirmed that users can export data with various date ranges and filter options.

## Screenshots
<img width="1433" alt="Screenshot 2024-10-13 at 4 58 53 AM" src="https://github.com/user-attachments/assets/74ce6f32-95c5-4aba-8ffc-fe7fd29c502d">
<img width="1433" alt="Screenshot 2024-10-13 at 4 59 09 AM" src="https://github.com/user-attachments/assets/863a86ec-9c9d-4760-9b4f-bb3637be0ca1">
<img width="1433" alt="Screenshot 2024-10-13 at 4 59 30 AM" src="https://github.com/user-attachments/assets/e8c2c3fd-bed6-45f1-86e8-9755b45a0582">

**Comment by SpreadSheets600** [comment]
@yazdanhaider thank you for your amazing work, please open up a Pull Request 😊
