### ISSUE TITLE
[REFACTOR] -Separation of Concerns

### ISSUE THREAD

**Issue by ShearStress021** [SpreadSheets600/Budget-Tracker#18]
### Affected Code/Module

the whole app.py

### Reason for Refactor

**I would separate concerns. for instance database, logic and presentation are in same module, they need to be decouple**

### Expected Benefits

Readable and extensible code

**Comment by SpreadSheets600** [comment]
@ShearStress021 that would be great 😃

**Comment by ShearStress021** [comment]
**it not complete but i thought maybe i should share what i had done my you'll be interested to help refactor the code**

**Comment by SpreadSheets600** [comment]
> **it not complete but i thought maybe i should share what i had done my you'll be interested to help refactor the code**

@ShearStress021 yea i saw it, so i am working on it and i am almost done, it got a total ui change, thanks to @yazdanhaider for the ui design idea :)
