### ISSUE TITLE
[FEATURE] - Implement Currency Conversion feature to convert between currencies, pulling exchange rates from an API

### ISSUE THREAD

**Issue by Picodes10** [SpreadSheets600/Budget-Tracker#21]
### Feature Summary

 Convert between different currencies.

### Additional Context

This feature allows users to convert between currencies when adding or viewing expenses. It integrates with an external API to fetch real-time exchange rates. Users can input costs in any currency, which will be automatically converted to their preferred currency before being saved.

**Comment by SpreadSheets600** [comment]
@Picodes10 thank you, it would be really nice to have that feature.
