### ISSUE TITLE
[BUG] - Fix Notification Display

### ISSUE THREAD

**Issue by SpreadSheets600** [SpreadSheets600/Budget-Tracker#22]
### Bug Description

The Notification Display Isn't Properly Being Shown

### Steps to Reproduce

1. Fix The Display
2. Place It Properly
3. Improve It's Functionality

**Comment by 9x14S** [comment]
What's wrong with the notification display? Is it the notification that appears when logging in/registering?

**Comment by SpreadSheets600** [comment]
@9x14S yea the  position is wierd, but I am not sure cause my friend said he fixed it .... it was behind the label of the main section so it was not properly visible

**Comment by 9x14S** [comment]
Yep I saw what you mean. Sometimes the notification appears a bit to the right and half of it isn't visible.

By the way, I had this error repeat a lot of times while running the app:
![image](https://github.com/user-attachments/assets/c0e2fa7e-8e3b-413a-8341-9f297058cabd)

**Comment by SpreadSheets600** [comment]
@9x14S popup window not properly being handled, if you can look up or else i will look into it

**Comment by 9x14S** [comment]
I'll check it

**Comment by 9x14S** [comment]
@SpreadSheets600 Question: is there a way to somehow "link" a `CtkTopLevel` window to another? Or at least to get the coordinates of the main window? During my testing, I saw that not only does the popup notification sometimes appear positioned a bit weird but that if the window is minimized it just puts the popup somewhere random on the screen:
![image](https://github.com/user-attachments/assets/14f9b8e4-a09d-4a57-991f-f5bf8892bfbd)

**Comment by SpreadSheets600** [comment]
@9x14S thanks for fixing it up :0)
