### ISSUE TITLE
[BUG] - Fix Visualization Tab

### ISSUE THREAD

**Issue by SpreadSheets600** [SpreadSheets600/Budget-Tracker#23]
### Bug Description

Visualization Tab Isn't Looking Good

### Steps to Reproduce

1. Fix The Display
2. Improve The Positioning
3. Fix The Display Of The Graphs

**Comment by Cosmyccc** [comment]
Hey @SpreadSheets600 I would like to work on this issue.

**Comment by SpreadSheets600** [comment]
> Hey @SpreadSheets600 I would like to work on this issue.

I would be glad if you do :)

**Comment by Cosmyccc** [comment]
Hey @SpreadSheets600, Can you review the design of the visualization page and let me know if it's good or if any changes are needed? 
![Screenshot (191)](https://github.com/user-attachments/assets/8208b318-d7c1-49bc-9992-58f0585328c5)
![Screenshot (192)](https://github.com/user-attachments/assets/1d0839a6-f450-40a2-96d0-29588dd51422)
![Screenshot (193)](https://github.com/user-attachments/assets/b086a362-5f07-46a9-86df-4d48fb1267d5)

**Comment by SpreadSheets600** [comment]
@Rani1303 this is amazing
