### ISSUE TITLE
[REFACTOR] - Refactor Based On New Structure

### ISSUE THREAD

**Issue by SpreadSheets600** [SpreadSheets600/Budget-Tracker#25]
Even Though The The Code Is Quite Refactored, If It Can Be More Refactored It Would Be Helpful

**Comment by 9x14S** [comment]
More refactored how? What do you feel needs refactoring?

**Comment by SpreadSheets600** [comment]
@9x14S well not exactly, I feel it could be better organized with it... do you think should I close it ?

**Comment by 9x14S** [comment]
Looks well organized from what I see
