### ISSUE TITLE
`bcrypt` package is missing, `python_bcrypt` is provided instead + `Icon.ico` error

### ISSUE THREAD

**Issue by 9x14S** [SpreadSheets600/Budget-Tracker#31]
Hello! When setting up this repo, I had this problem: 
![image](https://github.com/user-attachments/assets/fc45fa7e-1694-4155-8e56-935b584f147f)
Which stems from missing the `bcrypt` module. 
I saw that in the `pyproject.toml` `python_bcrypt` is provided instead, which even though installed makes the file throw an exception. Installing that package manually fixed the bug though.

Also, when installing everything, I get this error: 
![image](https://github.com/user-attachments/assets/640c7c25-fa6d-4406-a7dd-1d5f3b71022c)
Which I think is because `Icon.ico` is a __Windows__ icon, and I'm using Linux

**Comment by SpreadSheets600** [comment]
@9x14S yea I get the .ico stuff, can it be replaced with something else what works on every os ?

**Comment by 9x14S** [comment]
From the traceback I think it just needs a regular bitmap file
