### ISSUE TITLE
[REFACTOR] - Suggestion to Add a .gitignore File to the Repository

### ISSUE THREAD

**Issue by ajaysharadkumar** [SpreadSheets600/Budget-Tracker#33]
### Affected Code/Module

.venv or maybe the .db file

### Reason for Refactor

I’ve been reviewing the repository, and I noticed that it currently does not include a .gitignore file. Having a .gitignore file in the project is beneficial to prevent accidental commits of files that are not relevant to the repository (e.g., log files, temporary build files, environment configurations, etc.).

### Expected Benefits

I believe adding this file will help streamline contributions and prevent unwanted files from cluttering the repository. Some common entries for .gitignore could include:

IDE configurations (e.g., .vscode/, .idea/)
Log files (e.g., *.log)
Temporary or build artifacts (e.g., *.out, *.o)
Environment and configuration files (e.g., .env)

### Additional Context

I would be happy to work on creating and submitting a .gitignore file if you'd like. Please let me know if you're open to this, and I can proceed with a pull request.

Thank you for considering this suggestion, and I look forward to your feedback.

Best regards,
Ajay

**Comment by 9x14S** [comment]
This project desperately needs a .gitignore to stop tracking __pycache__ folders

**Comment by SpreadSheets600** [comment]
@ajaysharadkumar holy it does .... i had it but i did not push it .... the one who did the .env, he did not add it though i am assigning this to @ajaysharadkumar

**Comment by ajaysharadkumar** [comment]
@SpreadSheets600 I noticed that the option to create a branch directly from this issue isn't available. Could you confirm if this setting has been disabled?

**Comment by SpreadSheets600** [comment]
> @SpreadSheets600 I noticed that the option to create a branch directly from this issue isn't available. Could you confirm if this setting has been disabled?

it is available

**Comment by ajaysharadkumar** [comment]
> > @SpreadSheets600 I noticed that the option to create a branch directly from this issue isn't available. Could you confirm if this setting has been disabled?
> 
> it is available

I can't see it 
![image](https://github.com/user-attachments/assets/f718544e-b6c1-455b-a39c-95de0c4a50a0)
